### ISSUE TITLE
Register API

### ISSUE THREAD

**Issue by intoro** [glassechidna/fwdform2#1]
When registering a user from the command line

I run:
`curl --data "email=<your_email>&password=<your_password>" <WEB_URL>/register`
But returns:
`Mailgun Magnificent API`
Instead of:
`Public token: <public_token>, Private token: <private_token>`

any ideas? Do I need to have a specific email and password? Thanks!

I am trying to get a token for the web form action parameters

**Comment by Benjamin-Dobell** [comment]
@intoro Does your `WEB_URL` look something like `https://yourappname.herokuapp.com`?

**Comment by intoro** [comment]
`https://firmform.herokuapp.com/register
`
yup, thanks, now I get:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>
```
But it doesnt ask for credentials

**Comment by Benjamin-Dobell** [comment]
I was able to recreate this if I post to Mailgun's API directly, rather than the Heroku app.

i.e. You **don't** want the following:

```
curl --data "email=test@test.com&password=somepassword" https://api.mailgun.net/register
```

Instead you want:


```
curl --data "email=test@test.com&password=somepassword" https://firmform.herokuapp.com/register
```

The difference being that in the first example I'm erroneously posting to Mailgun's API. You need to make sure you're posting to your Heroku app.

**Comment by Benjamin-Dobell** [comment]
Sorry, just realised you've updated your post above.

> But it doesnt ask for credentials

The credential is provided as the `password` parameter. In the example above I've used the password "somepassword", which probably isn't the password you've setup. The password you submit has to match the `REGISTRATION_PASSWORD` that you've set.

You can view (and change it) from the Heroku control panel. In your case that'll be available at https://dashboard.heroku.com/apps/firmform/settings

Then press "Reveal Config Vars". From here you'll want to make sure:

`REGISTRATION_ENABLED` = 'yes'
`REGISTRATION_PASSWORD` = '<whatever super-dooper secret password you're using>`

Just make sure you submit that exact same password when registering a user.

It's probably worth noting this password is just stored in clear text. So I would probably advise that you use a different password than you use for your personal stuff. Someone still needs to gain access to your Heroku account to view it... but just in case!

**Comment by intoro** [comment]
Thanks Benjamin, I will be testing all this out tonight and will update with the results

**Comment by intoro** [comment]
Thank you for the clarification, I was able to receive the Tokens using your instructions. So Awesome!

**Comment by Benjamin-Dobell** [comment]
Glad to hear. 😄

I've added some additional information to the README, in particular a small "Troubleshooting" section, if submitting a form doesn't work, and also added information explaining how to redirect users (back to your webpage) after submitting a form.

Hopefully it's smooth sailing from here on out.

**Comment by intoro** [comment]
Thanks! Nice job on the code!
